services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  service.identity:
    build:
      context: .
      dockerfile: service.identity/Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 9000:80

volumes:
  postgres_data:
    driver: local
